name: DLang

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: mihails-strasuns/setup-dlang@v0
    - name: Build
      run: dub build
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
             blog-sbarratt
             public/
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

