name: DLang

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: mihails-strasuns/setup-dlang@v0
    - name: Build
      run: dub build
    - name: Make-Release-Archive
      run: tar-files.sh
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: release.tar.gz
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

